# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Dev Release

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci ignore')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt-hotspot
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get data
        id: metadata
        run: |
          echo ::set-output name=VERSION::$(php -r 'echo explode("+", explode("-", yaml_parse_file(getcwd() . DIRECTORY_SEPARATOR . "src/main/resources/version.yml")["version"])[0])[0];')
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bedrockcloud
          path: target/BedrockCloud.jar
      - name: Upload development release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development Release v${{ steps.metadata.outputs.VERSION }}"
          files: |
            target/Cloud.jar